import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { doc, setDoc, updateDoc } from 'firebase/firestore';
import { db } from '../config/firebase';
import { BookingData } from './BookingForm';
import { Button } from '../app/components/ui/button';
import { Card } from '../app/components/ui/card';
import { ArrowLeft, CreditCard, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

interface PaymentProps {
  bookingData: BookingData;
  onBack: () => void;
  onSuccess: (bookingId: string) => void;
}

// Razorpay types
declare global {
  interface Window {
    Razorpay: any;
  }
}

export default function Payment({ bookingData, onBack, onSuccess }: PaymentProps) {
  const [loading, setLoading] = useState(false);
  const { currentUser } = useAuth();

  const loadRazorpayScript = () => {
    return new Promise((resolve) => {
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve(true);
      script.onerror = () => resolve(false);
      document.body.appendChild(script);
    });
  };

  const handlePayment = async () => {
    if (!currentUser) {
      toast.error('Please login to continue');
      return;
    }

    setLoading(true);

    try {
      // Load Razorpay script
      const scriptLoaded = await loadRazorpayScript();

      if (!scriptLoaded) {
        toast.error('Failed to load payment gateway');
        setLoading(false);
        return;
      }

      // Generate booking ID
      const bookingId = `BK${Date.now()}${Math.random().toString(36).substr(2, 9).toUpperCase()}`;

      // Create booking document in Firestore
      await setDoc(doc(db, 'bookings', bookingId), {
        id: bookingId,
        userId: currentUser.uid,
        restaurantId: bookingData.restaurantId,
        restaurantName: bookingData.restaurantName,
        date: bookingData.date,
        time: bookingData.time,
        guests: bookingData.guests,
        amount: bookingData.amount,
        status: 'pending',
        createdAt: new Date().toISOString()
      });

      // Razorpay options
      const options = {
        key: 'rzp_test_SkWtabfopTbhAO', // Replace with your Razorpay Key ID
        amount: bookingData.amount * 100, // Amount in paise
        currency: 'INR',
        name: 'TableBook',
        description: `Table booking at ${bookingData.restaurantName}`,
        order_id: '', // Will be generated by your backend in production
        handler: async function (response: any) {
          // Payment successful
          try {
            // Update booking status to confirmed
            await updateDoc(doc(db, 'bookings', bookingId), {
              status: 'confirmed'
            });

            // Store payment data
            const paymentId = `PAY${Date.now()}${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
            await setDoc(doc(db, 'payments', paymentId), {
              id: paymentId,
              userId: currentUser.uid,
              bookingId: bookingId,
              amount: bookingData.amount,
              paymentStatus: 'success',
              transactionId: response.razorpay_payment_id,
              createdAt: new Date().toISOString()
            });

            toast.success('Payment successful!');
            onSuccess(bookingId);
          } catch (error) {
            console.error('Error updating booking:', error);
            toast.error('Payment received but booking update failed');
          }
        },
        prefill: {
          name: currentUser.displayName || '',
          email: currentUser.email || '',
          contact: ''
        },
        theme: {
          color: '#DC2626'
        },
        modal: {
          ondismiss: function () {
            setLoading(false);
            toast.error('Payment cancelled');
          }
        }
      };

      const razorpay = new window.Razorpay(options);
      razorpay.open();
      setLoading(false);
    } catch (error: any) {
      console.error('Payment error:', error);
      toast.error(error.message || 'Payment failed');
      setLoading(false);
    }
  };

  // For demo/testing: simulate payment without Razorpay
  const handleDemoPayment = async () => {
    if (!currentUser) {
      toast.error('Please login to continue');
      return;
    }

    setLoading(true);

    try {
      // Generate booking ID
      const bookingId = `BK${Date.now()}${Math.random().toString(36).substr(2, 9).toUpperCase()}`;

      // Create booking document in Firestore
      await setDoc(doc(db, 'bookings', bookingId), {
        id: bookingId,
        userId: currentUser.uid,
        restaurantId: bookingData.restaurantId,
        restaurantName: bookingData.restaurantName,
        date: bookingData.date,
        time: bookingData.time,
        guests: bookingData.guests,
        amount: bookingData.amount,
        status: 'confirmed',
        createdAt: new Date().toISOString()
      });

      // Store demo payment data
      const paymentId = `PAY${Date.now()}${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
      await setDoc(doc(db, 'payments', paymentId), {
        id: paymentId,
        userId: currentUser.uid,
        bookingId: bookingId,
        amount: bookingData.amount,
        paymentStatus: 'success',
        transactionId: `DEMO_${Date.now()}`,
        createdAt: new Date().toISOString()
      });

      toast.success('Demo payment successful!');
      onSuccess(bookingId);
    } catch (error: any) {
      console.error('Demo payment error:', error);
      toast.error(error.message || 'Payment failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-white shadow-sm sticky top-16 z-40">
        <div className="container mx-auto px-4 py-3">
          <Button
            variant="ghost"
            onClick={onBack}
            className="flex items-center gap-2"
            disabled={loading}
          >
            <ArrowLeft size={20} />
            Back
          </Button>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8 max-w-2xl">
        <h1 className="text-3xl font-bold mb-8">Payment</h1>

        <Card className="p-6 mb-6">
          <h2 className="text-xl font-semibold mb-4">Booking Summary</h2>
          <div className="space-y-3">
            <div className="flex justify-between">
              <span className="text-gray-600">Restaurant</span>
              <span className="font-medium">{bookingData.restaurantName}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-600">Date</span>
              <span className="font-medium">
                {new Date(bookingData.date).toLocaleDateString('en-IN', {
                  weekday: 'short',
                  year: 'numeric',
                  month: 'short',
                  day: 'numeric'
                })}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-600">Time</span>
              <span className="font-medium">{bookingData.time}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-600">Guests</span>
              <span className="font-medium">{bookingData.guests}</span>
            </div>
            <div className="flex justify-between pt-3 border-t mt-3">
              <span className="text-xl font-bold">Total Amount</span>
              <span className="text-xl font-bold text-green-600">
                ₹{bookingData.amount}
              </span>
            </div>
          </div>
        </Card>

        <Card className="p-6">
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <CreditCard size={24} />
            Payment Method
          </h2>

          <div className="space-y-4">
            <Button
              onClick={handlePayment}
              disabled={loading}
              className="w-full"
              size="lg"
            >
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Processing...
                </>
              ) : (
                'Pay with Razorpay'
              )}
            </Button>

            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-white px-2 text-gray-500">Or for demo</span>
              </div>
            </div>

            <Button
              onClick={handleDemoPayment}
              disabled={loading}
              variant="outline"
              className="w-full"
              size="lg"
            >
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Processing...
                </>
              ) : (
                'Demo Payment (Test Mode)'
              )}
            </Button>

            <p className="text-xs text-gray-500 text-center">
              Use demo payment to test the booking flow without real payment
            </p>
          </div>
        </Card>

        <p className="text-sm text-gray-500 mt-6 text-center">
          Your payment is secure and encrypted. We don't store your card details.
        </p>
      </div>
    </div>
  );
}
